(define (sqrt x)
  (define (sqrt-iter guess)
    (define (average x y)
      (/ (+ x y) 2)
    )
    (define (good-enough? guess)
      (< (abs (- (square guess) x)) 0.001)
    ) 
    (define (improve guess)
      (average guess (/ x guess))
    )
    (if (good-enough? guess)
      guess
      (sqrt-iter (improve guess))
    )
  )

  (sqrt-iter 1)
)

(sqrt 2)